# Generated by Django 4.0.2 on 2022-03-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receita_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
